version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    # Disable automatic updates for complex TypeScript packages
    ignore:
      - dependency-name: "@modelcontextprotocol/*"
      - dependency-name: "@types/*"
      - dependency-name: "typescript"
      - dependency-name: "prettier"
      - dependency-name: "eslint*"
    # Only allow updates for our simple server dependencies
    allow:
      - dependency-name: "express"
      - dependency-name: "cors"
